### ISSUE TITLE
Compatibility with Xiaomi (Xiaofang )cam?

### ISSUE THREAD

**Issue by mgf909** [HclX/WyzeHacks#1]
This looks really great. I have a XiaoFang WiFi Camera..
Any idea if your firmware is compatible with this hardware?

**Comment by HclX** [comment]
I'm not sure, I don't have a xiaofang camera to try this out. Please try it and let me know if it works.

**Comment by HclX** [comment]
Actually, i don't think this will work with Xiaomi device as they use different software. This hack is based on Wyze firmware.
