### ISSUE TITLE
FTP Access

### ISSUE THREAD

**Issue by FredFlintstoneLOL** [HclX/WyzeHacks#11]
How difficult would it be to make a fork that leaves the SD card intact but runs an FTP server so that we get both local storage and the opportunity to grab the recordings for more redundancy instead of relying on the NFS share availability?

**Comment by tomatensaus** [comment]
you will have too compile the binary in this format

ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV)

**Comment by HclX** [comment]
check the dafang hacks firmware, I believe they have ftp daemon somewhere, or at least the compilation toolchain to build a ftp server for this device.
