### ISSUE TITLE
Wyze Cam default telnet credentials

### ISSUE THREAD

**Issue by lilchancep** [HclX/WyzeHacks#112]
Does anyone have a list of all the cameras default telnet credentials after the hack is installed?

**Comment by HclX** [comment]
The default credential differs per each camera model, v2 camera is "ismart12", v3 camera is "WYom2020 ", pan camera is unknown. If you enable the password shadow setting, wyzehack will override the password to "ismart12" for all supported models.

**Comment by lilchancep** [comment]
@HclX thank you so much. You can close this.
