### ISSUE TITLE
Installing on v3 from SD card ?

### ISSUE THREAD

**Issue by gszakacs** [HclX/WyzeHacks#116]
Readme is not clear whether installing from SD card is an option for v3 but I am guessing it isn't. I copied the content of the latest release zip (wyze_hacks_0_5_06.zip) onto an SD card (adjust the config.inc file and rebooting cam. No luck. Am I correct assuming that the wyzehacks can't be installed on v3 from SD card ?
Thanks

**Comment by HclX** [comment]
@gszakacs  You are correct: SD card installation is no longer working for all models with their recent firmware. So the first installation needs to be done with remote_install.sh.
