### ISSUE TITLE
[Feature Request] Reboot on ping Fail?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [HclX/WyzeHacks#119]
Can you implement a feature in the config that if an address cannot be ping'd (ie; 192.168.1.1) for like 60 seconds that the camera will reboot?

Thank you.

**Comment by HclX** [comment]
Don't we already have NFS disconnect detection?

**Comment by BiatuAutMiahn** [comment]
> Don't we already have NFS disconnect detection?

It does recover as far as I can tell, nonetheless this would still be a useful feature

**Comment by endertable** [comment]
You can use the custom script feature Wyzehacks has and just create your own script for this.  If you don’t know shelol scripting let me know, I can lead you to some that have already been written for similar purpose.

**Comment by BiatuAutMiahn** [comment]
The custom script applies only if NFS mount is active right?

**Comment by endertable** [comment]
If you edit /configs/WyzeHacks.sh, youcan put a call to your script in there and end it with an ampersand to let it run in background as a daemon and monitor the network, and restart network or reboot cam as needed.  Of course, first thing in your script should be a sleep 60 to allow iCamera to do the initial network startup.

**Comment by BiatuAutMiahn** [comment]
ok, thank you
