### ISSUE TITLE
After going back to factory firmware, telnet still enabled with default root password

### ISSUE THREAD

**Issue by netjeff** [HclX/WyzeHacks#12]
I got one of my cameras updated to WyzeHacks firmware.  But I was having some problems.  

So I decided to go back to factory 4.9.5.36.  After following official instructions https://support.wyzecam.com/hc/en-us/articles/360031490871-How-to-flash-firmware-manually, I noticed that I can still telnet into the camera.  But now with the default root password.   I'm definitely back on the stock firmware, because there is no /tmp/boot.log like there was with the WyzeHacks firmware.  So it seems like my cam is on a mix of this and factory firmware?  How do I get all the way back to factory firmware?  Or at least turn off telnet?

**Comment by HclX** [comment]
unfortunately that seems to be a by design behavior: flashing firmware manually will not clear all the settings. I think you can try a factory reset but I don't know if that works. If it doesn't work, you can manually telnet into the device and run "rm -f /configs/.Server_config" to turn it off.

**Comment by HclX** [comment]
telnet settings should be the only thing left after that. Once turned off, you are now fully back to factory firmware.
