### ISSUE TITLE
root password

### ISSUE THREAD

**Issue by devianpctek** [HclX/WyzeHacks#2]
What is the root default password? Or do I have to generate one in order to use telnet?

**Comment by thompatry** [comment]
According the the documentation, it is ismart12.

https://github.com/HclX/WyzeHacks/blob/master/info/sdcard_hack.md

**Comment by devianpctek** [comment]
> According the the documentation, it is ismart12.
> 
> https://github.com/HclX/WyzeHacks/blob/master/info/sdcard_hack.md

Thanks
