### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by revans23** [HclX/WyzeHacks#22]
I am unable to install.  I unzip the appropriate files and edit the config file.  I go through the install process and the voice prompts.  Then the installation fails and the log returns:

> Starting wyze hack installer...
> Enabling telnetd...
> umount: can't umount /etc: Invalid argument
> Current Wyze software version is 4.9.5.111
> Installing WyzeHacks version 0.3.00
> Configuration file not found, aborting...

Please help.

**Comment by HclX** [comment]
You need to rename the config file template to "config.inc".
