### ISSUE TITLE
Enable telnet access only

### ISSUE THREAD

**Issue by ajn142** [HclX/WyzeHacks#26]
Is it possible within the current config file to enable telnet access only, without making other modifications? I’m wanting to poke around the camera OS a bit, without losing the ability to record to the local SD card. If not, could this be considered for a later enhancement?

**Comment by HclX** [comment]
Sorry, that's not supported. However, this entire project is open source so you can make a fork and modify it to whatever you want. If you are seriously thinking of looking into the OS, i suggest you open a camera and solder wires to the serial port. Trust me, that will give you quite a lot of convenience playing around.
