### ISSUE TITLE
No video recordings on NFS share but other files are created

### ISSUE THREAD

**Issue by HclX** [HclX/WyzeHacks#29]
There are multiple reports that on certain setups the NFS share is mounted correctly, some files are created, however, no video recordings. I suspect this has something to do with the NFS share size but will need more information on this since I don't have a large enough NFS share to test this out.

**Comment by HclX** [comment]
@kdvlr Let me know if you can post more information about your setup. I added more logging in latest change so can you try it and show me the log related to this. You will need to enable log syncing, and then search "statfs(path=" in the log to find the related debugging information.  Make sure you mask or erase your credentials.

**Comment by kdvlr** [comment]
@HclX - Did you make any changes to the NFS code ? I can see the recordings being created with your latest release.

**Comment by HclX** [comment]
Yes. I modified the code to change the emulated SD card max size from 2TB to 512GB, and looks like that's the root cause! I will keep this issue open for a couple more days until you confirm this really fixes the issue!

**Comment by HclX** [comment]
Mark this one fixed.
