### ISSUE TITLE
Config.INC Issue -  Need commented out

### ISSUE THREAD

**Issue by thompatry** [HclX/WyzeHacks#32]
These two lines needs commented out. If not it throws an error. I would fix it but I am mobile right now.

https://github.com/HclX/WyzeHacks/blob/abbddbf44b543370d3ecf48d800238e326e75c9e/installer/config.inc.TEMPLATE#L10-L11

**Comment by HclX** [comment]
darn it, i keep forgetting this, will fix it tonight.

**Comment by HclX** [comment]
this is fixed in latest release (0.4.1).
