### ISSUE TITLE
NFS mounted but nothing appears

### ISSUE THREAD

**Issue by 5tanly** [HclX/WyzeHacks#36]
I verified that the NFS share is mounted on the camera with telnet and on my server using the logs. I cant enable local recording in the app because it doesnt think there is an sd card installed. I tried it on a 4tb drive, and then I went down to a 500gb drive hoping it would fix. What troubleshooting steps can I take?

**Comment by thompatry** [comment]
What is your drive formatted as?

**Comment by 5tanly** [comment]
Ext4

**Comment by HclX** [comment]
which version of the hack are you running with? there was an issue with large NFS share, but it's fixed in later releases. I'd try thelatest release and see if it works.

**Comment by HclX** [comment]
closing this as i'm not hearing any update.
