### ISSUE TITLE
"No SD card" once SD card removed

### ISSUE THREAD

**Issue by ctjameson** [HclX/WyzeHacks#4]
I'm using the newest commit, never had any hacks installed. Followed instruction, once SD card is removed, Wyze cam shows no SD card inserted.

**Comment by HclX** [comment]
if you are using the latest firmware, yes, that will happen. I just made a change to fix that.

**Comment by ctjameson** [comment]
Oh hell yes! Updated my test cam using telnet and local repo, updated to newest firmware and bingo bongo, we're updated!

Thanks as always, HclX! Half of my house runs on your code. Lol.

**Comment by HclX** [comment]
marking this issue closed.
