### ISSUE TITLE
Modify naming of stored folder from just the MAC address?

### ISSUE THREAD

**Issue by cr08** [HclX/WyzeHacks#41]
Now that I've gotten this working quite well on my cameras, one glaring issue I see is relying on just the MAC address for naming of the stored folder on the NFS share and making it hard to track down if going in manually and not through the Wyze app.

I imagine the MAC is pulled on-camera after it has been flashed and used internally during the NFS mounting/writing process. Is it possible the 'friendly name' per the Wyze app is stored on camera somewhere and can be used? Maybe an additional config option for people to choose how they want it named. Or I'd even be happy with something like '<MACADDRESS>_<FriendlyName>'.

**Comment by HclX** [comment]
If you mean giving the camera NFS folder a friendly name, you can already do that: simply rename it to whatever you want and reboot the camera. Next time it will automatically find this folder and use that for all the recordings.
