### ISSUE TITLE
4.9.6.207 beta Firmware

### ISSUE THREAD

**Issue by revenant-81** [HclX/WyzeHacks#42]
Updating to 4.9.6.207 beta firmware causes the camera to not detect the NFS connection as an SD card even though the mount is still active and valid.

Downgrading to 4.9.6.199 works fine.

**Comment by gtxaspec** [comment]
Confirmed, same fw version v2 cam

**Comment by HclX** [comment]
yes, i did a brief look and it seems they made some changes to the bootstraping code, will see if i can get over that.

**Comment by Pcpro745** [comment]
@HclX any luck with this? Looks like its happening on the new stable firmware too.

**Comment by HclX** [comment]
I've drafted release 0.4.04 to support latest stable firmware (4.x.6.218), please try it and let me know if it works.

**Comment by unomar** [comment]
I built 0.4.04 from the dev branch and ran the remote_install.sh, but the cameras don't appear to be pulling the update.  Update from 0.4.03 on master still works though.

**Comment by HclX** [comment]
Yes there is a bug causing it not working when built from general linux environment. I've made a fix for that.

**Comment by gtxaspec** [comment]
confirm latest firmware working with fixed made to dev branch! thanks
