### ISSUE TITLE
Cannot upgrade hack using remote install

### ISSUE THREAD

**Issue by n1ckyrush** [HclX/WyzeHacks#44]
Just decided to share my experience, it might be useful for somebody. Also, there might be a bug with perms.

Goal: make some changes in hack sources (specifically, apply the change to adjust the volume via config from dev branch), build and upgrade some cam.

I've made some changes, then bumped version in `wyze_hack/hack_ver.inc`, then run `build.sh` script. Everything worked smooth, I've got `release/<MY_NEW_VER>`.

I tried the way with remote install, it worked pretty neatly for me for the initial install. So, I've run `remote_install.sh` in a new folder with a new version, run the process, it worked fine. But it didn't upgrade anything on camera.

So, I've tried the way with telnet install. I've copied the folder into NFS, and from camera run `telnet_install.sh` from that NFS folder. Then I saw this error: 
```/tmp/Upgrade/upgraderun.sh: line 8: /tmp/Upgrade/wyze_hack.sh: Permission denied```
So, I went to `telnet_install.sh` and added one line:
```
chmod +x /tmp/Upgrade/wyze_hack.sh
/tmp/Upgrade/upgraderun.sh
```
Then I run it again and it worked this time. The camera rebooted and I've got updated stuff in `/tmp/run/wyze_hack/hack_ver.inc` and all other files.

**Comment by HclX** [comment]
thanks for reporting this. Yes, i confirmed this is a bug in my build script. It wasn't reproducing in my environment due to my own special setup. I've made a fix.
