### ISSUE TITLE
SD card shows as "0.05 GB" on some cameras

### ISSUE THREAD

**Issue by ctjameson** [HclX/WyzeHacks#5]
Install works, folder appears on NAS, however the SD card shows a capacity of 0.05 GB instead of the 14TB that the others show. Still shows the same after rebooting a dozen times.

Running Wyze Cam v2 on latest commit on newest Wyze firmware (4.9.5.35)

**Comment by ctjameson** [comment]
Looks to be an issue with the newest firmware (4.9.5.36) as all cameras are now showing the same thing and none are recording. I guess that just shows I should have stayed on a lower FW. :/

**Comment by pumasight** [comment]
Now that they have a streaming  service....

**Comment by ctjameson** [comment]
Yup. Guess I need to find the older firmware somewhere and set them to
never update. :/

**Comment by ctjameson** [comment]
Reverted to 4.9.4.169 and everything is great again! Now to pull down all my cameras yet again. -_-

**Comment by stephenjamieson** [comment]
I had this issue with mounts above 2tb.  When I put a quota of 2tb on the ZFS dataset I was using for the nfs share it worked fine.  I tried 3tb and it broke, not sure what the limit is but 2tb is fine for me.  Note that it also broke `df`.

**Comment by ctjameson** [comment]
It’s actually fully fixed now in the newest revision so we’re all good.

**Comment by stephenjamieson** [comment]
Interesting, I definitely can't mount anything above 2tb on the latest but that's probably a limitation of the embedded version of linux it's running.

**Comment by ctjameson** [comment]
Weird. Mine is mounted to a 14TB NFS share on my Synology without any
issue. Newest firmware, newest hacks version.
