### ISSUE TITLE
SD Card not Available 4.9.6.218

### ISSUE THREAD

**Issue by Pcpro745** [HclX/WyzeHacks#50]
I have the latest firmware installed on my Wyze cams and i also have the latest hack installed on the cameras but the cameras show SD Card not available when trying to view playback. Telnet shows the share is mounted and it will update the share with the Mac and IfConfig files. The share is around 40TB. It used to work before the update.

**Comment by HclX** [comment]
I've drafted release 0.4.04 to support the this firmware, please try it and let me know if it works.

**Comment by HclX** [comment]
forgot to mention, it's currently on dev branch, please find the release zip file in the "release" directory of the source code.

**Comment by gtxaspec** [comment]
confirming, latest dev branch works great, NFS etc. working good.

thank you!

**Comment by Pcpro745** [comment]
Thanks!!! appreciate it.

**Comment by HclX** [comment]
This is now in latest release
