### ISSUE TITLE
Voice alerts VERY loud

### ISSUE THREAD

**Issue by twig123** [HclX/WyzeHacks#52]
The voice alerts are very loud (ex: when network connectivity is lost).

Is there a way to make these alerts quieter? or completely disable them?

**Comment by revenant-81** [comment]
The setting "NOTIFICATION_VOLUME" in config.inc was added as of 0.4.03 to adjust the volume of notifications.

**Comment by HclX** [comment]
As @revenant-81 mentioned, you can now adjust the volume to a level you are comfortable with. The feature is disabled with latest default configuration template.
