### ISSUE TITLE
Check Version of WyzeHacks installed

### ISSUE THREAD

**Issue by cessna** [HclX/WyzeHacks#57]
If I telnet into the wyzecam, is there a file I can check to see which version of WyzeHacks I have installed on it?

I also just wanted to add, thanks for all the work on this! It has been immensely useful as a solution to storing footate.

**Comment by gtxaspec** [comment]
cat /tmp/run/wyze_hack/hack_ver.inc

**Comment by HclX** [comment]
If you have log sync enabled, the hack version is also printed at the beginning of the boot log. I can also make modifications to output the current hack version to the camera folder.
