### ISSUE TITLE
Auto configure seems to lock in settings

### ISSUE THREAD

**Issue by lando-cal** [HclX/WyzeHacks#61]
I'm not sure what exactly is happening yet, but there's an issue with the config update.
At the moment, no matter what I do with new settings in a config file, or edit the one stored on the NFS share, it's reverting to the initial config where I enabled the automatic configuration.

**Comment by lando-cal** [comment]
So, I can't check much beyond this, as I don't have Telnet access (I didn't set the hash yet, and I don't know the defaults) but in the log, it's printing the existing configuration, rather then the new one, when it shows that it's found a new one. It's doing this when printing what it believes to be the new config, and again once printing what's been applied.

**Comment by twig123** [comment]
default credentials are listed in step 6 here:
https://github.com/HclX/WyzeHacks/blob/master/info/sdcard_hack.md

**Comment by lando-cal** [comment]
> 
> 
> default credentials are listed in step 6 here:
> https://github.com/HclX/WyzeHacks/blob/master/info/sdcard_hack.md

Thanks for that, not sure how I missed it.
After review, I've noticed that the configure function hooks the reboot, not startup. Rebooting the camera from the app or Telnet works fine. If it loses power and comes back online, however, this will overwrite any config intended to be retrieved by the camera.

**Comment by HclX** [comment]
this is fixed in release 0.5.01
