### ISSUE TITLE
telnet is disabled if NFS is not accessible

### ISSUE THREAD

**Issue by gtxaspec** [HclX/WyzeHacks#83]
Looks like telnet is disabled if the NFS share is not accessible...

re-did some configurations today and forgot to allow access to the VPN network...so the NFS share was not accessible from the camera.  This had the side effect of not enabling telnetd, so I incorrectly assumed it was a camera issue, instead of a network issue.  

verified on another camera, if NFS doesn't mount, telnet doesn't work.

**Comment by gtxaspec** [comment]
Just noticed there is a new bugfix release, I will try to see if the issue is fixed there!

**Comment by HclX** [comment]
no, it's not fixed yet. actually i just found this on my cameras, will come up with a fix in bugfix branch.

**Comment by HclX** [comment]
the fix is now in `bugfix` branch, please give it a try.

**Comment by gtxaspec** [comment]
confirmed fixed
