### ISSUE TITLE
How to detect a notification/alarm

### ISSUE THREAD

**Issue by tomatensaus** [HclX/WyzeHacks#9]
I have enabled the person detection and am recording to nfs, in the event of a person detected I would like to be able to execute a custom script. Do you have any idea where the events are recorded?

**Comment by HclX** [comment]
In the camera folder, you will see an "alarm" directory. Every time an alarm is triggered, a new snapshot picture will be stored into the "alarm" directory. So if your script is on a linux server, you can probably watch that directory using inotifywait and perform actions when a file is added. However, I don't know if you can do the same thing on camera as it doesn't have this tool.
