### ISSUE TITLE
NFS server on Wyze?

### ISSUE THREAD

**Issue by mrlt8** [HclX/WyzeHacks#96]
Hello, would it be possible to set an NFS server on the cam?

This could allow for scheduled transfers/backups by pulling the data to the NAS when needed instead of having to maintain a constant NFS connection between the camera and NAS/NFS server.

Somewhat related to https://github.com/HclX/WyzeHacks/issues/68 since the camera could always record to the internal SD and we could copy/delete the footage from the cam's SD over the network when the camera is reachable.

**Comment by HclX** [comment]
i don't think running nfs server on the camera is the right solution. starting a ssh server might be a better choice which you can already do it with custom script.
